version: "3.8"

services:
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-container
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - product-service
      - user-service
      - order-service
    networks:
      - microservices_default

  order-service:
    build: ./order-service
    container_name: order-service-container
    restart: always
    ports:
      - "3002:3002"
    networks:
      - microservices_default

  product-service:
    build: ./product-service
    container_name: product-service-container
    restart: always
    ports:
      - "3001:3001"
    networks:
      - microservices_default

  user-service:
    build: ./user-service
    container_name: user-service-container
    restart: always
    ports:
      - "3000:3000"
    networks:
      - microservices_default

networks:
  microservices_default:
    driver: bridge


